[project]
name = "nodeflow"
version = "0.1.0"
description = "A lightweight task flow utility."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.3",
    "pydantic>=2.11.7",
]
